version: "3"
services:
  m1:
    build:
      context: ./microservice1
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - microservices

  m2:
    build:
      context: ./microservice2
    depends_on:
      - rabbitmq
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices

networks:
  microservices:
